### ISSUE TITLE
Pure number vectors are note pure

### ISSUE THREAD

**Issue by nico202** [Keno/SIUnits.jl#101]
Hi,
If i multiply
    [1Hz] * 3s
I get a
    1-element Array{SIUnits.SIQuantity{Int64,m,kg,s,A,K,mol,cd,rad,sr},1}:
that cannot be used with function like sin() etc since its a SIUnits array, while it should become pure like 1Hz*3s does

**Comment by tlycken** [comment]
What package and Julia version are you on? (If you run `versioninfo()` and `Pkg.status("SIUnits")` in the REPL, what's the output?)

On Julia 0.5.0 with SIUnits 0.1.0, I can't reproduce:

```jl
julia> [1Hz] * 3s
1-element Array{Int64,1}:
 3
```

**Comment by nico202** [comment]
```
julia> Pkg.status("SIUnits")
 - SIUnits                       0.1.0
```

julia 0.4.6

**Comment by tlycken** [comment]
I did some digging, and the difference seems to stem from the improvements to array comprehensions (and array operations in general) that were introduced with Julia 0.5.

**Comment by nico202** [comment]
Cool to know that language improvements works then :) Really need to upgrade
